## this workflow is for testing a build with rider binaries and can serve instead of running plugin verifier
## on rider because it compiles all code with rider binaries and not with idea binaries.
## we don't need the build artifacts from this workflow, and they are not uploaded to github.

name: Build Rider main branch
on:
  workflow_call:
    inputs:
      build-profile:
        required: true
        type: string
#    secrets:
#      posthog-token-url:
#        required: true

jobs:

  build:

    name: Build with Rider
    runs-on: ubuntu-latest

    steps:

      - name: Fetch Sources
        uses: actions/checkout@v3
        with:
          ref: 'main'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.411

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Build Plugin
        env:
          POSTHOG_TOKEN_URL: ${{ secrets.POSTHOG_TOKEN_URL}}
        run: ./gradlew clean test buildPlugin -PbuildWithRider=true -PbuildProfile=${{ inputs.build-profile }} -PdoNotDownloadSources=true --no-configuration-cache
