
name: Manual workflow

on:
  workflow_dispatch:

jobs:
  check-release-exists:
    runs-on: ubuntu-22.04
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Delete old tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete v2.0.101 -y
